### ISSUE TITLE
Current selection will be delete when entering repeat count.

### ISSUE THREAD

**Issue by ricje** [bfrascher/Sublime-nRepeat#1] opened 2014-03-14 15:40 UTC
I'd like to be able to move a selected block of line up or down n lines using Ctrl+Shift+Up/Down with nRepeat. I can do it for a single line, but If I have a selected block of text, it doesn't work.

How to reproduce:

select a block of text
press alt-r
enter 5

result:
the selected text is deleted.

expected result:
I can enter a count and execute the next command on this selected text block.

**Comment by bfrascher** [comment] 2014-03-14 21:47
Hi ricje,
I have fixed the issue on my developer version, but the fix causes a small oddity in the plugins behaviour when working with multiple selection regions. I'll have to take another look at that tomorrow and hopefully will be able to release the new version then.

**Comment by bfrascher** [comment] 2014-03-15 09:17
The issue is fixed as of version 0.1.2.

**Closed as completed by bfrascher** 2014-03-15 09:17 UTC
